### ISSUE TITLE
首页搜索提示框 and word card

### ISSUE THREAD

**Issue by TechQuery** [Leidenschaft/Dictionary-PWA#1]
功能参考：http://leidenschaft.cn/django/static/

**Comment by zhaofeng-shu33** [comment]
I think this search module could also be used for main frame pages when searching new words

**Comment by TechQuery** [comment]
为了更好地**适配移动端**，实际开发时没做传统的输入提示框，而是直接展示**词条卡片**，后面会在点击卡片后进入新页面显示详情：

![image](https://user-images.githubusercontent.com/19969570/96440944-3ff01080-123b-11eb-9730-d5e986ce7364.png)

**Comment by zhaofeng-shu33** [comment]
all right
